### ISSUE TITLE
Exception during hot deploy

### ISSUE THREAD

**Issue by Wodric** [stagemonitor/stagemonitor-mailinglist#15]
Hi,

Until now with my project poker-league (see my profile) hot deploy don't thrown exception. But during my test with stagemonitor I had a big exception stack (see below) during hot deploy.  
This stack is repeat maybe doyen times. Do you know an issue with hot deploying? Is my application with are not correctly set ?

When I restart my tomcat or go several time on my application it doesn't occured any more until the next hot deployment.

Technical information about my projet:
- It's a vaadin project on last vaadin version (7.5.3)
- I use Java 8
- I use SLF4J 1.7.11
- I use stage monitor 0.17.1

Thanks,
Alexandre

<pre>

août 16, 2015 9:54:54 AM org.apache.catalina.loader.WebappClassLoaderBase checkStateForResourceLoading
INFOS: Illegal access: this web application instance has been stopped already. Could not load [org.class]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.class]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1335)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1026)
	at org.stagemonitor.javassist.LoaderClassPath.find(LoaderClassPath.java:87)
	at org.stagemonitor.javassist.ClassPoolTail.find(ClassPoolTail.java:354)
	at org.stagemonitor.javassist.ClassPool.find(ClassPool.java:589)
	at org.stagemonitor.javassist.ClassPool.createCtClass(ClassPool.java:573)
	at org.stagemonitor.javassist.ClassPool.get0(ClassPool.java:538)
	at org.stagemonitor.javassist.ClassPool.get(ClassPool.java:447)
	at org.stagemonitor.javassist.compiler.MemberResolver.lookupClass0(MemberResolver.java:478)
	at org.stagemonitor.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:410)
	at org.stagemonitor.javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:275)
	at org.stagemonitor.javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:913)
	at org.stagemonitor.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:870)
	at org.stagemonitor.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at org.stagemonitor.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at org.stagemonitor.javassist.compiler.ast.Expr.accept(Expr.java:68)
	at org.stagemonitor.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:860)
	at org.stagemonitor.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at org.stagemonitor.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at org.stagemonitor.javassist.compiler.ast.Expr.accept(Expr.java:68)
	at org.stagemonitor.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:860)
	at org.stagemonitor.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at org.stagemonitor.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at org.stagemonitor.javassist.compiler.ast.Expr.accept(Expr.java:68)
	at org.stagemonitor.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:860)
	at org.stagemonitor.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at org.stagemonitor.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at org.stagemonitor.javassist.compiler.ast.Expr.accept(Expr.java:68)
	at org.stagemonitor.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at org.stagemonitor.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at org.stagemonitor.javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at org.stagemonitor.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at org.stagemonitor.javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at org.stagemonitor.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at org.stagemonitor.javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at org.stagemonitor.javassist.CtBehavior.insertBefore(CtBehavior.java:754)
	at org.stagemonitor.javassist.CtBehavior.insertBefore(CtBehavior.java:734)
	at org.stagemonitor.requestmonitor.profiler.ProfilingInstrumenter.transformClass(ProfilingInstrumenter.java:50)
	at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.transformWithJavassist(MainStagemonitorClassFileTransformer.java:139)
	at org.stagemonitor.core.instrument.MainStagemonitorClassFileTransformer.transform(MainStagemonitorClassFileTransformer.java:111)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2476)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:857)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1282)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1164)
	at elemental.json.impl.JreJsonFactory.createArray(JreJsonFactory.java:48)
	at elemental.json.Json.createArray(Json.java:34)
	at com.vaadin.data.RpcDataProviderExtension.pushRowData(RpcDataProviderExtension.java:940)
	at com.vaadin.data.RpcDataProviderExtension.beforeClientResponse(RpcDataProviderExtension.java:898)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:113)
	at com.vaadin.server.communication.UIInitHandler.getInitialUidl(UIInitHandler.java:285)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:80)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.stagemonitor.web.monitor.MonitoredHttpRequest.execute(MonitoredHttpRequest.java:194)
	at org.stagemonitor.requestmonitor.RequestMonitor.monitor(RequestMonitor.java:162)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.monitorRequest(HttpRequestMonitorFilter.java:169)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.doMonitor(HttpRequestMonitorFilter.java:126)
	at org.stagemonitor.web.monitor.filter.HttpRequestMonitorFilter.doFilterInternal(HttpRequestMonitorFilter.java:100)
	at org.stagemonitor.web.monitor.filter.AbstractExclusionFilter.doFilter(AbstractExclusionFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
<pre>

**Comment by Wodric** [comment]
Like usually, I explain the issue and I doesn't reproduce any more after resetting my configurations. 
Sorry for this post.

**Comment by felixbarny** [comment]
Maybe you have been using an older version of stagemonitor which had issues with redeploys.

**Comment by Wodric** [comment]
That's not impossible, I begin with 0.13.0 version. Maybe some dependancy was not change.
Thanks for answer
